apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-lsnl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-lsnl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-lsnl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-lsnl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-lsnl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pbco-tenant/rhtap-demo-app/hacbs-test-project-lsnl@sha256:5ca24747bdf17907f87fe3c2423db113100c59ce491b39edbe1890ac5093dee9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
