apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lsnl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pbco-tenant/rhtap-demo-app/hacbs-test-project-lsnl@sha256:5c4aae396c893a90fed79c4ecf8418b1222336ae53c252db2172e7f63d983b6c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
